#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: "3"

services:
  apisix:
    image: apache/apisix:${APISIX_IMAGE_TAG:-3.7.0-debian}
    restart: always
    volumes:
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    ##network_mode: host
    ports:
      - "9180:9180/tcp"
      - "9080:9080/tcp"
      - "9091:9091/tcp"
      - "9443:9443/tcp"
      - "9092:9092/tcp"
    networks:
      apisix:

  etcd:
    image: bitnami/etcd:3.4.15
    restart: always
    volumes:
      - etcd_data:/bitnami/etcd
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379/tcp"
    networks:
      apisix:

  web1:
    image: nginx:1.19.0-alpine
    restart: always
    volumes:
      - ./upstream/web1.conf:/etc/nginx/nginx.conf
    ports:
      - "9081:80/tcp"
    environment:
      - NGINX_PORT=80
    networks:
      apisix:

  web2:
    image: nginx:1.19.0-alpine
    restart: always
    volumes:
      - ./upstream/web2.conf:/etc/nginx/nginx.conf
    ports:
      - "9082:80/tcp"
    environment:
      - NGINX_PORT=80
    networks:
      apisix:

  prometheus:
    image: prom/prometheus:v2.25.0
    restart: always
    volumes:
      - ./prometheus_conf/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      apisix:

  grafana:
    image: grafana/grafana:7.3.7
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - "./grafana_conf/provisioning:/etc/grafana/provisioning"
      - "./grafana_conf/dashboards:/var/lib/grafana/dashboards"
      - "./grafana_conf/config/grafana.ini:/etc/grafana/grafana.ini"
    networks:
      apisix:
  mysql:
    image: mysql:5.7.37
    platform: linux/amd64
    networks:
      apisix:
    environment:
      MYSQL_ROOT_PASSWORD: gh123456
      MYSQL_ROOT_HOST: '%'
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_general_ci',
      '--port=3306',
    ]
    ports:
      - 3306:3306
    volumes:
      - ./scripts/migration:/data/all-in-one/migration
    restart: always
  redis:
    image: redis:5.0.14-alpine
    networks:
      apisix:
    ports:
      - 6379:6379
    restart: always
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9099:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.3.22
      KAFKA_CREATE_TOPICS: ""
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    links:
      - zookeeper

  clickhouse:
    image: yandex/clickhouse-server:21.3.20-alpine
    container_name: clickhouse
    restart: always
    networks:
      - apisix
    ports:
      - "8123:8123"
      - "9999:9000"
    volumes:
      # 默认配置
      - ./clickhouse/config/docker_related_config.xml:/etc/clickhouse-server/config.d/docker_related_config.xml:rw
      - ./clickhouse/config/config.xml:/etc/clickhouse-server/config.xml:rw
      - ./clickhouse/config/users.xml:/etc/clickhouse-server/users.xml:rw
      - /etc/localtime:/etc/localtime:ro
      # 运行日志
      - ${LOGS_PATH_HOST}/clickhouse/log:/var/log/clickhouse-server
      # 数据持久
      - ${DATA_PATH_HOST}/clickhouse:/var/lib/clickhouse:rw
      - ${CODE_PATH_HOST}:/code

  mongo:
    image: mongo:latest
    restart: always
    networks:
      - apisix
    ports:
      - 27017:27017
    volumes:
      - /etc/localtime:/etc/localtime
      - ${DATA_PATH_HOST}/mongodb:/data
      - ${CODE_PATH_HOST}:/code
    privileged: true
    environment:
      TZ: ${TZ}
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456

networks:
  apisix:
    driver: bridge

volumes:
  etcd_data:
    driver: local
